name: deploy-manual

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'select deploy'
        required: true
        default: 'test1'
        type: choice
        options:
          - test1
          - check-env
      deploy-message:
        description: 'firebase deploy message -m'
        required: false
        type: string

env:
  NODE_VERSION: 16.x
  DEPLOY_TARGET: ${{ github.event.inputs.deploy }}
  DEPLOY_BRANCH: ${{ github.ref_name }}
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:
  test1:
    if: ${{ github.event.inputs.deploy == 'test1' }}
    name: deploy test1
    runs-on: ubuntu-latest
    env:
      FF: ${{ secrets.FIREBASE_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.DEPLOY_BRANCH }}
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: node version
        run: |
          node -v
      
      - name: env test1
        run: echo "${{ env.FIREBASE_TOKEN }}"
      - name: env test2
        run: echo "${{ env.FF }}"
      - name: env test3
        run: echo "$FF"
        
      - name: gen-num
        id: gen
        run: echo "::set-output name=x::${{inputs.deploy}}"
      - if: steps.gen.outputs.x == 'test1'
        run: echo "test test"
      - if: steps.gen.outputs.x == 'check-env'
        run: echo "chekc env eheck env"
        
      - run: echo "This job's branch is ${{ job.branch }}"
      - run: echo "this job event is ${{ job.event }}"
      - name: test1 code
        if: ${{ job.status == 'success' }}
        run: echo "completed !!!!!"
        
      - name: npm build
        id: build
        continue-on-error: true
        run: |
          npm ci
          npm run build
      - name: build check
        if: ${{ always() }}
        run: echo "${{ steps.build.conclusion }}"
      - name: firebase deploy
        if: ${{ success() }}
        run: |
          npx firebase-tools deploy --token $FIREBASE_TOKEN --non-interactive --only hosting:aimmo-ojt -m "${{ inputs.deploy-message }}"
      - name: failed!
        if: ${{ failure() }}
        run: echo "실패 했습니다!"
        
      - run: echo "This job's status is ${{ job.status }}."
  check-env:
    name: check-list
    runs-on: ubuntu-latest
    steps:
      - run: echo " github.event_name -  ${{ github.event_name }}"
      - run: echo " runner.os - ${{ runner.os }}"
      - run: echo " github.ref - ${{ github.ref }}"
      - run: echo " github.repository - ${{ github.repository }}"
      - run: echo " github.ref_name - ${{ github.ref_name }}"
      - run: echo " secrets.FIREBASE_TOKEN - ${{ secrets.FIREBASE_TOKEN }}"
      - run: echo " github.event.inputs.deploy - ${{ github.event.inputs.deploy }}"
      - name: Check out repository code - actions/checkout@v3
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

